// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4bMh-5wvASLBpENjdixxr93-umlrHUtM',
    appId: '1:95330482761:web:e95b1275d89f6dc2299d98',
    messagingSenderId: '95330482761',
    projectId: 'whatsappclone-backend-be8ff',
    authDomain: 'whatsappclone-backend-be8ff.firebaseapp.com',
    storageBucket: 'whatsappclone-backend-be8ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGVYoE58CerVN1yPrsC2yBCsHGcfM_KrQ',
    appId: '1:95330482761:android:fd5430a9330d7000299d98',
    messagingSenderId: '95330482761',
    projectId: 'whatsappclone-backend-be8ff',
    storageBucket: 'whatsappclone-backend-be8ff.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNwmQTPVMGbrSxu123-ouWVESc2kxQlb4',
    appId: '1:95330482761:ios:974f693755bce3be299d98',
    messagingSenderId: '95330482761',
    projectId: 'whatsappclone-backend-be8ff',
    storageBucket: 'whatsappclone-backend-be8ff.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNwmQTPVMGbrSxu123-ouWVESc2kxQlb4',
    appId: '1:95330482761:ios:974f693755bce3be299d98',
    messagingSenderId: '95330482761',
    projectId: 'whatsappclone-backend-be8ff',
    storageBucket: 'whatsappclone-backend-be8ff.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4bMh-5wvASLBpENjdixxr93-umlrHUtM',
    appId: '1:95330482761:web:eca3e4f3e7eb75e3299d98',
    messagingSenderId: '95330482761',
    projectId: 'whatsappclone-backend-be8ff',
    authDomain: 'whatsappclone-backend-be8ff.firebaseapp.com',
    storageBucket: 'whatsappclone-backend-be8ff.firebasestorage.app',
  );

}